### ISSUE TITLE
多个trigger，若element已经显示，切换trigger时element不能正常显示

### ISSUE THREAD

**Issue by vinz08** [aralejs/popup#27]
多个trigger，若element已经显示，切换trigger时element不能正常显示，效果是先显示一下再隐藏掉了，triggerType: 'focus' 才会是这样，click 和 focus不会。

**Comment by vinz08** [comment]
···
_bindFocus: function() {
      var that = this;
      bindEvent('focus', this.get('trigger'), function() {
        // 标识当前点击的元素
        that.activeTrigger = $(this);
       // 添加的代码 https://github.com/aralejs/popup/issues/27
        var delay = that.get('delay');
        setTimeout(function() {
            that.show();
          }, delay);
        //that.show(); 之前的代码
      }, this.get('delegateNode'), this);
      bindEvent('blur', this.get('trigger'), function() {
        setTimeout(function() {
          (!that._downOnElement) && that.hide();
          that._downOnElement = false;
        }, that.get('delay'));
      }, this.get('delegateNode'), this);
      // 为了当input blur时能够选择和操作弹出层上的内容
      this.delegateEvents("mousedown", function(e) {
        this._downOnElement = true;
      });
    }
···

**Comment by afc163** [comment]
的确有这个问题，我看看先。

**Comment by afc163** [comment]
http://docs.spmjs.io/arale-popup/latest/examples/triggers.html#%E8%8C%83%E4%BE%8B3-%E5%A4%9A-triggers-%E5%92%8C-blurhide-%E5%85%B1%E5%AD%98%E7%9A%84%E9%97%AE%E9%A2%98

Focus 的例子，感谢反馈。
